version: "3.8"

services:
  nginx:
    image: your-dockerhub-username/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - public-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./certbot-entrypoint.sh:/usr/bin/certbot-entrypoint.sh
    entrypoint: "/bin/sh -c '/usr/bin/certbot-entrypoint.sh'"
    networks:
      - public-network

  react:
    image: your-dockerhub-username/react:latest
    container_name: react
    networks:
      - internal-network
    depends_on:
      - backend
    restart: on-failure

  backend:
    image: your-dockerhub-username/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      PORT: ${BACKEND_PORT}
    networks:
      - internal-network
    restart: always

  backend_2:
    image: your-dockerhub-username/backend:latest
    container_name: backend_2
    ports:
      - "8081:8080"
    environment:
      PORT: ${BACKEND_PORT}
    networks:
      - internal-network
    restart: always

  backend_3:
    image: your-dockerhub-username/backend:latest
    container_name: backend_3
    ports:
      - "8082:8080"
    environment:
      PORT: ${BACKEND_PORT}
    networks:
      - internal-network
    restart: always
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 300
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "watchtower@yourdomain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "your_email@example.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtp.your-email-provider.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "your_email@example.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD_FILE: /run/secrets/watchtower_email_password
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 50
    restart: unless-stopped
    networks:
      - internal-network
    secrets:
      - watchtower_email_password

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge

secrets:
  watchtower_email_password:
    file: ./secrets/watchtower_email_password.txt
