version: "3.8"
services:
  mongodb:
    image: mongo:4.4  
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always  

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    depends_on:
      - backend

  react:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    restart: on-failure

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      PORT: ${BACKEND_PORT}
    networks:
      - app-network
    depends_on:
      - mongodb
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: