name: CI

on:
  push:
    branches:
      - main
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display changes
        run: |
          git log --pretty=format:"%h - %an, %ar : %s" -5 > changes.log
          cat changes.log

      - name: Get Repository Name
        run: |
          REPO_NAME=$(basename `git rev-parse --show-toplevel`)
          echo "Repository Name: $REPO_NAME" >> changes.log

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_CONTENT=$(git log -1 --pretty=format:"%s")
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Changes have been pushed to the repository $REPO_NAME by $AUTHOR. Here is the latest commit: $COMMIT_CONTENT", "embeds": [{"title": "Recent Commits", "description": "$(cat changes.log)"}]}' $DISCORD_WEBHOOK